# 2023.09.25 Conclusion. 여기서는 "라우터" 기능만 하고,
# "local", "dev", "prod", 즉, "local=로컬 컴퓨터=H2 DB", "dev=개발용 서버=MySQL", "prod=운영 서버=Oracle" 이렇게 구분하여,
# .yml 파일을 관리한다.

---
spring:
  profiles:
    active: prod
    # 위의 "local", "dev", "prod" 위에 "공백"이 있으면, 에러 나는 경우도 있다.

---
jasypt:
  encryptor:
    # config/JasyptConfig.java 파일에서 @Bean("jasyptStringEncryptor") 어노테이션 값과 반드시 동일한 값으로 등록해 주어야 한다. [등록명과 동일하게 맞추어 준다]
    bean: jasyptStringEncryptor

---
application:
  security:
    jwt:
      secret-key: 462D4A614E645266556A586E3272357538782F413F4428472B4B625065536856
      expiration: 86400000 # 60000 # 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days



# 2023.09.27 IT 늦공 application.yml

#--- # Start
#
#--- # change port
#server:
#  port: 8085
#
#--- # mvc view
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views
#      suffix: .jsp
#
#--- # devtools
#spring:
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#
#---  #oracle settings
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: scott
#    password: tiger
#
#--- #mybatis mapper xml
#mybatis:
#  mapper-locations: classpath:sqlmapper/*.xml
#  configuration.map-underscore-to-camel-case: true



# 2024.02.06 Added. 얼쑤 ALLSSU 참조
# https://www.youtube.com/watch?v=hHRLN9j1kqI&list=PLkaAEQyMpRg-k-PZDKvqw7EChwJQXxhkI&index=1
# [React/Spring Boot] ToDoList #1 - 강의 소개, 개발 환경 세팅

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/powerppsc
#    username: sa
#    password: "*963210z"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        show_sql: true
#        fromat_sql: true
#        use_sql_comments: true
